name: precommit_test
on:
  push:
    branches: [ main ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
      - uses: actions/checkout@v2
      - run : echo "111" > ${github.workspace}}/a.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pos_binary
          path: |
            ${{github.workspace}}/a.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pos_log
          path: |
            ${{github.workspace}}/a.txt
  unittest:
    name: unit_test
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  iosystemtest:
    name: io_system_level_test
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  nportest:
    name: npor_test
    needs: [build]
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  sportest:
    name: spor_test
    needs: [build]
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  rebuildtest:
    name: rebuild_test
    needs: [build]
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  volumetest:
    name: volume_test
    needs: [build]
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"
  wbttest:
    name: wbt_test
    needs: [build]
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - run : echo "hello"

